# Generated by Django 5.1.1 on 2024-09-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romaji_text', models.CharField(max_length=255)),
                ('hiragana_text', models.CharField(blank=True, max_length=255)),
                ('katakana_text', models.CharField(blank=True, max_length=255)),
                ('romaji_from_hiragana', models.CharField(blank=True, max_length=255)),
                ('romaji_from_katakana', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
